// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteLibrarianUsernameUserUserUsernameOKCode is the HTTP code returned for type DeleteLibrarianUsernameUserUserUsernameOK
const DeleteLibrarianUsernameUserUserUsernameOKCode int = 200

/*DeleteLibrarianUsernameUserUserUsernameOK Deleted

swagger:response deleteLibrarianUsernameUserUserUsernameOK
*/
type DeleteLibrarianUsernameUserUserUsernameOK struct {
}

// NewDeleteLibrarianUsernameUserUserUsernameOK creates DeleteLibrarianUsernameUserUserUsernameOK with default headers values
func NewDeleteLibrarianUsernameUserUserUsernameOK() *DeleteLibrarianUsernameUserUserUsernameOK {

	return &DeleteLibrarianUsernameUserUserUsernameOK{}
}

// WriteResponse to the client
func (o *DeleteLibrarianUsernameUserUserUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
