// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteLibrarianUsernameBookTitleAuthorOKCode is the HTTP code returned for type DeleteLibrarianUsernameBookTitleAuthorOK
const DeleteLibrarianUsernameBookTitleAuthorOKCode int = 200

/*DeleteLibrarianUsernameBookTitleAuthorOK Deleted

swagger:response deleteLibrarianUsernameBookTitleAuthorOK
*/
type DeleteLibrarianUsernameBookTitleAuthorOK struct {
}

// NewDeleteLibrarianUsernameBookTitleAuthorOK creates DeleteLibrarianUsernameBookTitleAuthorOK with default headers values
func NewDeleteLibrarianUsernameBookTitleAuthorOK() *DeleteLibrarianUsernameBookTitleAuthorOK {

	return &DeleteLibrarianUsernameBookTitleAuthorOK{}
}

// WriteResponse to the client
func (o *DeleteLibrarianUsernameBookTitleAuthorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
