// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBookTitleOKCode is the HTTP code returned for type DeleteBookTitleOK
const DeleteBookTitleOKCode int = 200

/*DeleteBookTitleOK Deleted

swagger:response deleteBookTitleOK
*/
type DeleteBookTitleOK struct {
}

// NewDeleteBookTitleOK creates DeleteBookTitleOK with default headers values
func NewDeleteBookTitleOK() *DeleteBookTitleOK {

	return &DeleteBookTitleOK{}
}

// WriteResponse to the client
func (o *DeleteBookTitleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
