// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteLibrarianUsernameBookTitleAuthorCopiesOKCode is the HTTP code returned for type DeleteLibrarianUsernameBookTitleAuthorCopiesOK
const DeleteLibrarianUsernameBookTitleAuthorCopiesOKCode int = 200

/*DeleteLibrarianUsernameBookTitleAuthorCopiesOK Deleted

swagger:response deleteLibrarianUsernameBookTitleAuthorCopiesOK
*/
type DeleteLibrarianUsernameBookTitleAuthorCopiesOK struct {
}

// NewDeleteLibrarianUsernameBookTitleAuthorCopiesOK creates DeleteLibrarianUsernameBookTitleAuthorCopiesOK with default headers values
func NewDeleteLibrarianUsernameBookTitleAuthorCopiesOK() *DeleteLibrarianUsernameBookTitleAuthorCopiesOK {

	return &DeleteLibrarianUsernameBookTitleAuthorCopiesOK{}
}

// WriteResponse to the client
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
