// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteBookTitleHandlerFunc turns a function with the right signature into a delete book title handler
type DeleteBookTitleHandlerFunc func(DeleteBookTitleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBookTitleHandlerFunc) Handle(params DeleteBookTitleParams) middleware.Responder {
	return fn(params)
}

// DeleteBookTitleHandler interface for that can handle valid delete book title params
type DeleteBookTitleHandler interface {
	Handle(DeleteBookTitleParams) middleware.Responder
}

// NewDeleteBookTitle creates a new http.Handler for the delete book title operation
func NewDeleteBookTitle(ctx *middleware.Context, handler DeleteBookTitleHandler) *DeleteBookTitle {
	return &DeleteBookTitle{Context: ctx, Handler: handler}
}

/* DeleteBookTitle swagger:route DELETE /book/{title} deleteBookTitle

delete a book by its title

*/
type DeleteBookTitle struct {
	Context *middleware.Context
	Handler DeleteBookTitleHandler
}

func (o *DeleteBookTitle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBookTitleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
