// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteLibrarianUsernameBookTitleAuthorHandlerFunc turns a function with the right signature into a delete librarian username book title author handler
type DeleteLibrarianUsernameBookTitleAuthorHandlerFunc func(DeleteLibrarianUsernameBookTitleAuthorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteLibrarianUsernameBookTitleAuthorHandlerFunc) Handle(params DeleteLibrarianUsernameBookTitleAuthorParams) middleware.Responder {
	return fn(params)
}

// DeleteLibrarianUsernameBookTitleAuthorHandler interface for that can handle valid delete librarian username book title author params
type DeleteLibrarianUsernameBookTitleAuthorHandler interface {
	Handle(DeleteLibrarianUsernameBookTitleAuthorParams) middleware.Responder
}

// NewDeleteLibrarianUsernameBookTitleAuthor creates a new http.Handler for the delete librarian username book title author operation
func NewDeleteLibrarianUsernameBookTitleAuthor(ctx *middleware.Context, handler DeleteLibrarianUsernameBookTitleAuthorHandler) *DeleteLibrarianUsernameBookTitleAuthor {
	return &DeleteLibrarianUsernameBookTitleAuthor{Context: ctx, Handler: handler}
}

/* DeleteLibrarianUsernameBookTitleAuthor swagger:route DELETE /librarian/{username}/book/{title}/{author} deleteLibrarianUsernameBookTitleAuthor

delete a book by its title/author

*/
type DeleteLibrarianUsernameBookTitleAuthor struct {
	Context *middleware.Context
	Handler DeleteLibrarianUsernameBookTitleAuthorHandler
}

func (o *DeleteLibrarianUsernameBookTitleAuthor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteLibrarianUsernameBookTitleAuthorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
