// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteLibrarianUsernameUserUserOKCode is the HTTP code returned for type DeleteLibrarianUsernameUserUserOK
const DeleteLibrarianUsernameUserUserOKCode int = 200

/*DeleteLibrarianUsernameUserUserOK Deleted

swagger:response deleteLibrarianUsernameUserUserOK
*/
type DeleteLibrarianUsernameUserUserOK struct {
}

// NewDeleteLibrarianUsernameUserUserOK creates DeleteLibrarianUsernameUserUserOK with default headers values
func NewDeleteLibrarianUsernameUserUserOK() *DeleteLibrarianUsernameUserUserOK {

	return &DeleteLibrarianUsernameUserUserOK{}
}

// WriteResponse to the client
func (o *DeleteLibrarianUsernameUserUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
