// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/swagger/models"
)

// GetLibrarianUsernameUserUserOKCode is the HTTP code returned for type GetLibrarianUsernameUserUserOK
const GetLibrarianUsernameUserUserOKCode int = 200

/*GetLibrarianUsernameUserUserOK Retrieved

swagger:response getLibrarianUsernameUserUserOK
*/
type GetLibrarianUsernameUserUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetLibrarianUsernameUserUserOK creates GetLibrarianUsernameUserUserOK with default headers values
func NewGetLibrarianUsernameUserUserOK() *GetLibrarianUsernameUserUserOK {

	return &GetLibrarianUsernameUserUserOK{}
}

// WithPayload adds the payload to the get librarian username user user o k response
func (o *GetLibrarianUsernameUserUserOK) WithPayload(payload *models.User) *GetLibrarianUsernameUserUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get librarian username user user o k response
func (o *GetLibrarianUsernameUserUserOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLibrarianUsernameUserUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
