// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/swagger/models"
)

// GetBookTitleOKCode is the HTTP code returned for type GetBookTitleOK
const GetBookTitleOKCode int = 200

/*GetBookTitleOK Retrieved

swagger:response getBookTitleOK
*/
type GetBookTitleOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewGetBookTitleOK creates GetBookTitleOK with default headers values
func NewGetBookTitleOK() *GetBookTitleOK {

	return &GetBookTitleOK{}
}

// WithPayload adds the payload to the get book title o k response
func (o *GetBookTitleOK) WithPayload(payload *models.Book) *GetBookTitleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get book title o k response
func (o *GetBookTitleOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookTitleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
