// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostBookHandlerFunc turns a function with the right signature into a post book handler
type PostBookHandlerFunc func(PostBookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBookHandlerFunc) Handle(params PostBookParams) middleware.Responder {
	return fn(params)
}

// PostBookHandler interface for that can handle valid post book params
type PostBookHandler interface {
	Handle(PostBookParams) middleware.Responder
}

// NewPostBook creates a new http.Handler for the post book operation
func NewPostBook(ctx *middleware.Context, handler PostBookHandler) *PostBook {
	return &PostBook{Context: ctx, Handler: handler}
}

/* PostBook swagger:route POST /book postBook

request a book be added to the library

*/
type PostBook struct {
	Context *middleware.Context
	Handler PostBookHandler
}

func (o *PostBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBookParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
