// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostLibrarianUsernameBookHandlerFunc turns a function with the right signature into a post librarian username book handler
type PostLibrarianUsernameBookHandlerFunc func(PostLibrarianUsernameBookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLibrarianUsernameBookHandlerFunc) Handle(params PostLibrarianUsernameBookParams) middleware.Responder {
	return fn(params)
}

// PostLibrarianUsernameBookHandler interface for that can handle valid post librarian username book params
type PostLibrarianUsernameBookHandler interface {
	Handle(PostLibrarianUsernameBookParams) middleware.Responder
}

// NewPostLibrarianUsernameBook creates a new http.Handler for the post librarian username book operation
func NewPostLibrarianUsernameBook(ctx *middleware.Context, handler PostLibrarianUsernameBookHandler) *PostLibrarianUsernameBook {
	return &PostLibrarianUsernameBook{Context: ctx, Handler: handler}
}

/* PostLibrarianUsernameBook swagger:route POST /librarian/{username}/book postLibrarianUsernameBook

request a book be added to the library

*/
type PostLibrarianUsernameBook struct {
	Context *middleware.Context
	Handler PostLibrarianUsernameBookHandler
}

func (o *PostLibrarianUsernameBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostLibrarianUsernameBookParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
