// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostBookCreatedCode is the HTTP code returned for type PostBookCreated
const PostBookCreatedCode int = 201

/*PostBookCreated Created

swagger:response postBookCreated
*/
type PostBookCreated struct {
}

// NewPostBookCreated creates PostBookCreated with default headers values
func NewPostBookCreated() *PostBookCreated {

	return &PostBookCreated{}
}

// WriteResponse to the client
func (o *PostBookCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
