// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutBookTitleOKCode is the HTTP code returned for type PutBookTitleOK
const PutBookTitleOKCode int = 200

/*PutBookTitleOK Updated

swagger:response putBookTitleOK
*/
type PutBookTitleOK struct {
}

// NewPutBookTitleOK creates PutBookTitleOK with default headers values
func NewPutBookTitleOK() *PutBookTitleOK {

	return &PutBookTitleOK{}
}

// WriteResponse to the client
func (o *PutBookTitleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
