// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLibrarianUsernameBookTitleAuthorParams creates a new DeleteLibrarianUsernameBookTitleAuthorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLibrarianUsernameBookTitleAuthorParams() *DeleteLibrarianUsernameBookTitleAuthorParams {
	return &DeleteLibrarianUsernameBookTitleAuthorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorParamsWithTimeout creates a new DeleteLibrarianUsernameBookTitleAuthorParams object
// with the ability to set a timeout on a request.
func NewDeleteLibrarianUsernameBookTitleAuthorParamsWithTimeout(timeout time.Duration) *DeleteLibrarianUsernameBookTitleAuthorParams {
	return &DeleteLibrarianUsernameBookTitleAuthorParams{
		timeout: timeout,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorParamsWithContext creates a new DeleteLibrarianUsernameBookTitleAuthorParams object
// with the ability to set a context for a request.
func NewDeleteLibrarianUsernameBookTitleAuthorParamsWithContext(ctx context.Context) *DeleteLibrarianUsernameBookTitleAuthorParams {
	return &DeleteLibrarianUsernameBookTitleAuthorParams{
		Context: ctx,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorParamsWithHTTPClient creates a new DeleteLibrarianUsernameBookTitleAuthorParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLibrarianUsernameBookTitleAuthorParamsWithHTTPClient(client *http.Client) *DeleteLibrarianUsernameBookTitleAuthorParams {
	return &DeleteLibrarianUsernameBookTitleAuthorParams{
		HTTPClient: client,
	}
}

/* DeleteLibrarianUsernameBookTitleAuthorParams contains all the parameters to send to the API endpoint
   for the delete librarian username book title author operation.

   Typically these are written to a http.Request.
*/
type DeleteLibrarianUsernameBookTitleAuthorParams struct {

	// Author.
	Author string

	// Title.
	Title string

	// Username.
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete librarian username book title author params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithDefaults() *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete librarian username book title author params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithTimeout(timeout time.Duration) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithContext(ctx context.Context) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithHTTPClient(client *http.Client) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthor adds the author to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithAuthor(author string) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetAuthor(author)
	return o
}

// SetAuthor adds the author to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetAuthor(author string) {
	o.Author = author
}

// WithTitle adds the title to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithTitle(title string) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetTitle(title string) {
	o.Title = title
}

// WithUsername adds the username to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WithUsername(username string) *DeleteLibrarianUsernameBookTitleAuthorParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete librarian username book title author params
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLibrarianUsernameBookTitleAuthorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param author
	if err := r.SetPathParam("author", o.Author); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
