// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteLibrarianUsernameUserUserReader is a Reader for the DeleteLibrarianUsernameUserUser structure.
type DeleteLibrarianUsernameUserUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLibrarianUsernameUserUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLibrarianUsernameUserUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteLibrarianUsernameUserUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLibrarianUsernameUserUserOK creates a DeleteLibrarianUsernameUserUserOK with default headers values
func NewDeleteLibrarianUsernameUserUserOK() *DeleteLibrarianUsernameUserUserOK {
	return &DeleteLibrarianUsernameUserUserOK{}
}

/* DeleteLibrarianUsernameUserUserOK describes a response with status code 200, with default header values.

Deleted
*/
type DeleteLibrarianUsernameUserUserOK struct {
}

func (o *DeleteLibrarianUsernameUserUserOK) Error() string {
	return fmt.Sprintf("[DELETE /librarian/{username}/user/{user}][%d] deleteLibrarianUsernameUserUserOK ", 200)
}

func (o *DeleteLibrarianUsernameUserUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLibrarianUsernameUserUserNotFound creates a DeleteLibrarianUsernameUserUserNotFound with default headers values
func NewDeleteLibrarianUsernameUserUserNotFound() *DeleteLibrarianUsernameUserUserNotFound {
	return &DeleteLibrarianUsernameUserUserNotFound{}
}

/* DeleteLibrarianUsernameUserUserNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteLibrarianUsernameUserUserNotFound struct {
}

func (o *DeleteLibrarianUsernameUserUserNotFound) Error() string {
	return fmt.Sprintf("[DELETE /librarian/{username}/user/{user}][%d] deleteLibrarianUsernameUserUserNotFound ", 404)
}

func (o *DeleteLibrarianUsernameUserUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
