// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteLibrarianUsernameBookTitleAuthorReader is a Reader for the DeleteLibrarianUsernameBookTitleAuthor structure.
type DeleteLibrarianUsernameBookTitleAuthorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLibrarianUsernameBookTitleAuthorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLibrarianUsernameBookTitleAuthorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorOK creates a DeleteLibrarianUsernameBookTitleAuthorOK with default headers values
func NewDeleteLibrarianUsernameBookTitleAuthorOK() *DeleteLibrarianUsernameBookTitleAuthorOK {
	return &DeleteLibrarianUsernameBookTitleAuthorOK{}
}

/* DeleteLibrarianUsernameBookTitleAuthorOK describes a response with status code 200, with default header values.

Deleted
*/
type DeleteLibrarianUsernameBookTitleAuthorOK struct {
}

func (o *DeleteLibrarianUsernameBookTitleAuthorOK) Error() string {
	return fmt.Sprintf("[DELETE /librarian/{username}/book/{title}/{author}][%d] deleteLibrarianUsernameBookTitleAuthorOK ", 200)
}

func (o *DeleteLibrarianUsernameBookTitleAuthorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
