// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteLibrarianUsernameBookTitleAuthorCopiesParams creates a new DeleteLibrarianUsernameBookTitleAuthorCopiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLibrarianUsernameBookTitleAuthorCopiesParams() *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	return &DeleteLibrarianUsernameBookTitleAuthorCopiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithTimeout creates a new DeleteLibrarianUsernameBookTitleAuthorCopiesParams object
// with the ability to set a timeout on a request.
func NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithTimeout(timeout time.Duration) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	return &DeleteLibrarianUsernameBookTitleAuthorCopiesParams{
		timeout: timeout,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithContext creates a new DeleteLibrarianUsernameBookTitleAuthorCopiesParams object
// with the ability to set a context for a request.
func NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithContext(ctx context.Context) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	return &DeleteLibrarianUsernameBookTitleAuthorCopiesParams{
		Context: ctx,
	}
}

// NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithHTTPClient creates a new DeleteLibrarianUsernameBookTitleAuthorCopiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLibrarianUsernameBookTitleAuthorCopiesParamsWithHTTPClient(client *http.Client) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	return &DeleteLibrarianUsernameBookTitleAuthorCopiesParams{
		HTTPClient: client,
	}
}

/* DeleteLibrarianUsernameBookTitleAuthorCopiesParams contains all the parameters to send to the API endpoint
   for the delete librarian username book title author copies operation.

   Typically these are written to a http.Request.
*/
type DeleteLibrarianUsernameBookTitleAuthorCopiesParams struct {

	// Author.
	Author string

	// Copies.
	Copies int64

	// Title.
	Title string

	// Username.
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete librarian username book title author copies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithDefaults() *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete librarian username book title author copies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithTimeout(timeout time.Duration) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithContext(ctx context.Context) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithHTTPClient(client *http.Client) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthor adds the author to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithAuthor(author string) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetAuthor(author)
	return o
}

// SetAuthor adds the author to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetAuthor(author string) {
	o.Author = author
}

// WithCopies adds the copies to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithCopies(copies int64) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetCopies(copies)
	return o
}

// SetCopies adds the copies to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetCopies(copies int64) {
	o.Copies = copies
}

// WithTitle adds the title to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithTitle(title string) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetTitle(title string) {
	o.Title = title
}

// WithUsername adds the username to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WithUsername(username string) *DeleteLibrarianUsernameBookTitleAuthorCopiesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete librarian username book title author copies params
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLibrarianUsernameBookTitleAuthorCopiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param author
	if err := r.SetPathParam("author", o.Author); err != nil {
		return err
	}

	// path param copies
	if err := r.SetPathParam("copies", swag.FormatInt64(o.Copies)); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
