// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLibrarianUsernameUserUserParams creates a new GetLibrarianUsernameUserUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLibrarianUsernameUserUserParams() *GetLibrarianUsernameUserUserParams {
	return &GetLibrarianUsernameUserUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibrarianUsernameUserUserParamsWithTimeout creates a new GetLibrarianUsernameUserUserParams object
// with the ability to set a timeout on a request.
func NewGetLibrarianUsernameUserUserParamsWithTimeout(timeout time.Duration) *GetLibrarianUsernameUserUserParams {
	return &GetLibrarianUsernameUserUserParams{
		timeout: timeout,
	}
}

// NewGetLibrarianUsernameUserUserParamsWithContext creates a new GetLibrarianUsernameUserUserParams object
// with the ability to set a context for a request.
func NewGetLibrarianUsernameUserUserParamsWithContext(ctx context.Context) *GetLibrarianUsernameUserUserParams {
	return &GetLibrarianUsernameUserUserParams{
		Context: ctx,
	}
}

// NewGetLibrarianUsernameUserUserParamsWithHTTPClient creates a new GetLibrarianUsernameUserUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLibrarianUsernameUserUserParamsWithHTTPClient(client *http.Client) *GetLibrarianUsernameUserUserParams {
	return &GetLibrarianUsernameUserUserParams{
		HTTPClient: client,
	}
}

/* GetLibrarianUsernameUserUserParams contains all the parameters to send to the API endpoint
   for the get librarian username user user operation.

   Typically these are written to a http.Request.
*/
type GetLibrarianUsernameUserUserParams struct {

	// User.
	User string

	// Username.
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get librarian username user user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLibrarianUsernameUserUserParams) WithDefaults() *GetLibrarianUsernameUserUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get librarian username user user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLibrarianUsernameUserUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) WithTimeout(timeout time.Duration) *GetLibrarianUsernameUserUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) WithContext(ctx context.Context) *GetLibrarianUsernameUserUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) WithHTTPClient(client *http.Client) *GetLibrarianUsernameUserUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) WithUser(user string) *GetLibrarianUsernameUserUserParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) SetUser(user string) {
	o.User = user
}

// WithUsername adds the username to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) WithUsername(username string) *GetLibrarianUsernameUserUserParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get librarian username user user params
func (o *GetLibrarianUsernameUserUserParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibrarianUsernameUserUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
