// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/client/models"
)

// GetBookTitleReader is a Reader for the GetBookTitle structure.
type GetBookTitleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBookTitleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBookTitleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBookTitleOK creates a GetBookTitleOK with default headers values
func NewGetBookTitleOK() *GetBookTitleOK {
	return &GetBookTitleOK{}
}

/* GetBookTitleOK describes a response with status code 200, with default header values.

Retrieved
*/
type GetBookTitleOK struct {
	Payload *models.Book
}

func (o *GetBookTitleOK) Error() string {
	return fmt.Sprintf("[GET /book/{title}][%d] getBookTitleOK  %+v", 200, o.Payload)
}
func (o *GetBookTitleOK) GetPayload() *models.Book {
	return o.Payload
}

func (o *GetBookTitleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Book)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
