// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"librarian/client/models"
)

// NewPostBookParams creates a new PostBookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostBookParams() *PostBookParams {
	return &PostBookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostBookParamsWithTimeout creates a new PostBookParams object
// with the ability to set a timeout on a request.
func NewPostBookParamsWithTimeout(timeout time.Duration) *PostBookParams {
	return &PostBookParams{
		timeout: timeout,
	}
}

// NewPostBookParamsWithContext creates a new PostBookParams object
// with the ability to set a context for a request.
func NewPostBookParamsWithContext(ctx context.Context) *PostBookParams {
	return &PostBookParams{
		Context: ctx,
	}
}

// NewPostBookParamsWithHTTPClient creates a new PostBookParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostBookParamsWithHTTPClient(client *http.Client) *PostBookParams {
	return &PostBookParams{
		HTTPClient: client,
	}
}

/* PostBookParams contains all the parameters to send to the API endpoint
   for the post book operation.

   Typically these are written to a http.Request.
*/
type PostBookParams struct {

	// Book.
	Book *models.Book

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBookParams) WithDefaults() *PostBookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post book params
func (o *PostBookParams) WithTimeout(timeout time.Duration) *PostBookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post book params
func (o *PostBookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post book params
func (o *PostBookParams) WithContext(ctx context.Context) *PostBookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post book params
func (o *PostBookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post book params
func (o *PostBookParams) WithHTTPClient(client *http.Client) *PostBookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post book params
func (o *PostBookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBook adds the book to the post book params
func (o *PostBookParams) WithBook(book *models.Book) *PostBookParams {
	o.SetBook(book)
	return o
}

// SetBook adds the book to the post book params
func (o *PostBookParams) SetBook(book *models.Book) {
	o.Book = book
}

// WriteToRequest writes these params to a swagger request
func (o *PostBookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Book != nil {
		if err := r.SetBodyParam(o.Book); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
