// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"librarian/client/models"
)

// NewPostLibrarianUsernameUserParams creates a new PostLibrarianUsernameUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostLibrarianUsernameUserParams() *PostLibrarianUsernameUserParams {
	return &PostLibrarianUsernameUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostLibrarianUsernameUserParamsWithTimeout creates a new PostLibrarianUsernameUserParams object
// with the ability to set a timeout on a request.
func NewPostLibrarianUsernameUserParamsWithTimeout(timeout time.Duration) *PostLibrarianUsernameUserParams {
	return &PostLibrarianUsernameUserParams{
		timeout: timeout,
	}
}

// NewPostLibrarianUsernameUserParamsWithContext creates a new PostLibrarianUsernameUserParams object
// with the ability to set a context for a request.
func NewPostLibrarianUsernameUserParamsWithContext(ctx context.Context) *PostLibrarianUsernameUserParams {
	return &PostLibrarianUsernameUserParams{
		Context: ctx,
	}
}

// NewPostLibrarianUsernameUserParamsWithHTTPClient creates a new PostLibrarianUsernameUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostLibrarianUsernameUserParamsWithHTTPClient(client *http.Client) *PostLibrarianUsernameUserParams {
	return &PostLibrarianUsernameUserParams{
		HTTPClient: client,
	}
}

/* PostLibrarianUsernameUserParams contains all the parameters to send to the API endpoint
   for the post librarian username user operation.

   Typically these are written to a http.Request.
*/
type PostLibrarianUsernameUserParams struct {

	// User.
	User *models.User

	// Username.
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post librarian username user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLibrarianUsernameUserParams) WithDefaults() *PostLibrarianUsernameUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post librarian username user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostLibrarianUsernameUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) WithTimeout(timeout time.Duration) *PostLibrarianUsernameUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) WithContext(ctx context.Context) *PostLibrarianUsernameUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) WithHTTPClient(client *http.Client) *PostLibrarianUsernameUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) WithUser(user *models.User) *PostLibrarianUsernameUserParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) SetUser(user *models.User) {
	o.User = user
}

// WithUsername adds the username to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) WithUsername(username string) *PostLibrarianUsernameUserParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the post librarian username user params
func (o *PostLibrarianUsernameUserParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *PostLibrarianUsernameUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
