// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutBookTitleReader is a Reader for the PutBookTitle structure.
type PutBookTitleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutBookTitleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutBookTitleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutBookTitleOK creates a PutBookTitleOK with default headers values
func NewPutBookTitleOK() *PutBookTitleOK {
	return &PutBookTitleOK{}
}

/* PutBookTitleOK describes a response with status code 200, with default header values.

Updated
*/
type PutBookTitleOK struct {
}

func (o *PutBookTitleOK) Error() string {
	return fmt.Sprintf("[PUT /book/{title}][%d] putBookTitleOK ", 200)
}

func (o *PutBookTitleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
