// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutLibrarianUsernameUserUserCheckinReader is a Reader for the PutLibrarianUsernameUserUserCheckin structure.
type PutLibrarianUsernameUserUserCheckinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLibrarianUsernameUserUserCheckinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutLibrarianUsernameUserUserCheckinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutLibrarianUsernameUserUserCheckinNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutLibrarianUsernameUserUserCheckinOK creates a PutLibrarianUsernameUserUserCheckinOK with default headers values
func NewPutLibrarianUsernameUserUserCheckinOK() *PutLibrarianUsernameUserUserCheckinOK {
	return &PutLibrarianUsernameUserUserCheckinOK{}
}

/* PutLibrarianUsernameUserUserCheckinOK describes a response with status code 200, with default header values.

Updated
*/
type PutLibrarianUsernameUserUserCheckinOK struct {
}

func (o *PutLibrarianUsernameUserUserCheckinOK) Error() string {
	return fmt.Sprintf("[PUT /librarian/{username}/user/{user}/checkin][%d] putLibrarianUsernameUserUserCheckinOK ", 200)
}

func (o *PutLibrarianUsernameUserUserCheckinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutLibrarianUsernameUserUserCheckinNotFound creates a PutLibrarianUsernameUserUserCheckinNotFound with default headers values
func NewPutLibrarianUsernameUserUserCheckinNotFound() *PutLibrarianUsernameUserUserCheckinNotFound {
	return &PutLibrarianUsernameUserUserCheckinNotFound{}
}

/* PutLibrarianUsernameUserUserCheckinNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutLibrarianUsernameUserUserCheckinNotFound struct {
}

func (o *PutLibrarianUsernameUserUserCheckinNotFound) Error() string {
	return fmt.Sprintf("[PUT /librarian/{username}/user/{user}/checkin][%d] putLibrarianUsernameUserUserCheckinNotFound ", 404)
}

func (o *PutLibrarianUsernameUserUserCheckinNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PutLibrarianUsernameUserUserCheckinBody put librarian username user user checkin body
swagger:model PutLibrarianUsernameUserUserCheckinBody
*/
type PutLibrarianUsernameUserUserCheckinBody struct {

	// author
	// Required: true
	Author *string `json:"author"`

	// title
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this put librarian username user user checkin body
func (o *PutLibrarianUsernameUserUserCheckinBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAuthor(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutLibrarianUsernameUserUserCheckinBody) validateAuthor(formats strfmt.Registry) error {

	if err := validate.Required("book"+"."+"author", "body", o.Author); err != nil {
		return err
	}

	return nil
}

func (o *PutLibrarianUsernameUserUserCheckinBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("book"+"."+"title", "body", o.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this put librarian username user user checkin body based on context it is used
func (o *PutLibrarianUsernameUserUserCheckinBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutLibrarianUsernameUserUserCheckinBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutLibrarianUsernameUserUserCheckinBody) UnmarshalBinary(b []byte) error {
	var res PutLibrarianUsernameUserUserCheckinBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
