// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"librarian/client/models"
)

// NewPutBookTitleParams creates a new PutBookTitleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBookTitleParams() *PutBookTitleParams {
	return &PutBookTitleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBookTitleParamsWithTimeout creates a new PutBookTitleParams object
// with the ability to set a timeout on a request.
func NewPutBookTitleParamsWithTimeout(timeout time.Duration) *PutBookTitleParams {
	return &PutBookTitleParams{
		timeout: timeout,
	}
}

// NewPutBookTitleParamsWithContext creates a new PutBookTitleParams object
// with the ability to set a context for a request.
func NewPutBookTitleParamsWithContext(ctx context.Context) *PutBookTitleParams {
	return &PutBookTitleParams{
		Context: ctx,
	}
}

// NewPutBookTitleParamsWithHTTPClient creates a new PutBookTitleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBookTitleParamsWithHTTPClient(client *http.Client) *PutBookTitleParams {
	return &PutBookTitleParams{
		HTTPClient: client,
	}
}

/* PutBookTitleParams contains all the parameters to send to the API endpoint
   for the put book title operation.

   Typically these are written to a http.Request.
*/
type PutBookTitleParams struct {

	// Book.
	Book *models.Book

	// Title.
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put book title params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookTitleParams) WithDefaults() *PutBookTitleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put book title params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBookTitleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put book title params
func (o *PutBookTitleParams) WithTimeout(timeout time.Duration) *PutBookTitleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put book title params
func (o *PutBookTitleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put book title params
func (o *PutBookTitleParams) WithContext(ctx context.Context) *PutBookTitleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put book title params
func (o *PutBookTitleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put book title params
func (o *PutBookTitleParams) WithHTTPClient(client *http.Client) *PutBookTitleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put book title params
func (o *PutBookTitleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBook adds the book to the put book title params
func (o *PutBookTitleParams) WithBook(book *models.Book) *PutBookTitleParams {
	o.SetBook(book)
	return o
}

// SetBook adds the book to the put book title params
func (o *PutBookTitleParams) SetBook(book *models.Book) {
	o.Book = book
}

// WithTitle adds the title to the put book title params
func (o *PutBookTitleParams) WithTitle(title string) *PutBookTitleParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the put book title params
func (o *PutBookTitleParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *PutBookTitleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Book != nil {
		if err := r.SetBodyParam(o.Book); err != nil {
			return err
		}
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
