swagger: "2.0"
info:
  title: "Library"
  version: "0.0.1"
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
paths:

  /librarian/{username}/book:
    post:
      summary: "request a book be added to the library"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
        - in: path
          name: username
          type: string
          required: true

      responses:
        '201':
          description: Created

  /librarian/{username}/book/{title}/{author}:
    delete:
      summary: "delete a book by its title/author"

      parameters:
        - in: path
          name: username
          type: string
          required: true
        - in: path
          name: title
          type: string
          required: true
        - in: path
          name: author
          type: string
          required: true

      responses:
        '200':
          description: Deleted

  /book:
    post:
      summary: "request a book be added to the library"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'

      responses:
        '201':
          description: Created

    get:
      summary: "request a book by its title"

      parameters:
        - in: query
          name: title
          required: true
          type: string

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/Book'

  /book/{title}:
    put:
      summary: "request a book be updated"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Updated

    get:
      summary: "request a book by its title"

      parameters:
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/Book'

    delete:
      summary: "delete a book by its title"

      parameters:
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Deleted

definitions:
    Book:
      description: A JSON object containing book information
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        copies:
          type: integer
        
        