swagger: "2.0"
info:
  title: "Library"
  version: "0.0.1"
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
paths:

  /librarian/{username}/user:
    post:
      summary: "request a user be added to the library"

      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
        - in: path
          name: username
          type: string
          required: true

      responses:
        '201':
          description: Created

  /librarian/{username}/user/{user}:

    get:
      summary: "request a user by their username"

      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: path
          name: user
          required: true
          type: string

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/User'
  
    delete:
      summary: "delete a user by their username"

      parameters:
        - in: path
          name: username
          type: string
          required: true
        - in: path
          name: user
          type: string
          required: true

      responses:
        '200':
          description: Deleted

  /librarian/{username}/book:
    post:
      summary: "request a book be added to the library"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
        - in: path
          name: username
          type: string
          required: true

      responses:
        '201':
          description: Created

  /librarian/{username}/book/{title}/{author}:

    get:
      summary: "request a books stock information by its title and author"

      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: path
          name: title
          required: true
          type: string
        - in: path
          name: author
          required: true
          type: string

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/BookStock'
   
  /librarian/{username}/book/{title}/{author}/{copies}:
    delete:
      summary: "delete a book by its title/author"

      parameters:
        - in: path
          name: username
          type: string
          required: true
        - in: path
          name: title
          type: string
          required: true
        - in: path
          name: author
          type: string
          required: true
        - in: path
          name: copies
          type: integer
          required: true

      responses:
        '200':
          description: Deleted

  /book:
    post:
      summary: "request a book be added to the library"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'

      responses:
        '201':
          description: Created

    get:
      summary: "request a book by its title"

      parameters:
        - in: query
          name: title
          required: true
          type: string

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/Book'

  /book/{title}:
    put:
      summary: "request a book be updated"

      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Updated

    get:
      summary: "request a book by its title"

      parameters:
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Retrieved
          schema:
            $ref: '#/definitions/Book'

    delete:
      summary: "delete a book by its title"

      parameters:
        - in: path
          name: title
          type: string
          required: true

      responses:
        '200':
          description: Deleted

definitions:
    Book:
      description: A JSON object containing book information
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        copies:
          type: integer
    BookStock:
      description: A JSON object containing book stock information
      type: object
      properties:
        copies:
          type: integer
        checkedout:
          type: integer
        instock:
          type: boolean
    User:
      description: A JSON object containing user information
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        